#!/bin/bash
set -e # stop on error
# set -x
WAS="${WAS:-https://storage.bengo.is}"
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SPACE_UUID="${SPACE_UUID:-$(cat "$SCRIPT_DIR/../default-space/uuid")}"
SPACE="$WAS/space/$SPACE_UUID"
ID="${ID:-$HOME/.ssh/wasup-react-router-default}"
WASUP_RR_CONTROLLER='did:key:z6MkwfVfRSyLfhXWpdAAdYdcpGZytmTHAtz2n4Fx94EUFnyo'
DEFAULT_CONTROLLER="${DEFAULT_CONTROLLER:-"$WASUP_RR_CONTROLLER"}"
CONTROLLER="${CONTROLLER:-"$DEFAULT_CONTROLLER"}"

space="$(./scripts/space.json.ts ${CONTROLLER+"--controller=$CONTROLLER"} ${SPACE_UUID+"--space=$SPACE_UUID"} )"
echo "$space"
wasup -i "$ID" --content-type application/json /dev/stdin "$SPACE"  <<< "$space"

linkset="$(./scripts/linkset.json.ts --space "$SPACE_UUID")"
wasup -i "$ID" --content-type application/linkset+json /dev/stdin "$SPACE"/linkset.json <<< "$linkset"

acl="$(./scripts/acl.json.ts)"
wasup -i "$ID" --content-type application/json /dev/stdin "$SPACE"/acl.json <<< "$acl"
